config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"enjoyments#index"
  resources :users, only: :show
  resources :targets, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :user

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  

  has_many :targets
  
  validates :name, presence: true
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  # def after_sign_in_path_for(resource)
  #   if current_user
  #     flash[:notice] = "ログインに成功しました" 
  #     user_path  #指定したいパスに変更
  #   else
  #     flash[:notice] = "新規登録完了しました。次に名前を入力してください" 
  #     new_profile_path  #指定したいパスに変更
  #   end
  # end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/enjoyments_controller.rb
class EnjoymentsController < ApplicationController
  def index
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  def index
    
  end

  def create
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def show
  # user = User.find(params[:id])
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enjoyments_helper.rb
module EnjoymentsHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/enjoyments/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# トップページの帯 %>
  <div class='top-content'>
    <h2 class='top-title'>
      Let's enjoy your life
    </h2>
  </div>

  <%# メッセージ %>
  <div class='middle-content'>
   <span class='maessage'>Massage</span>
  </div>

  <div class='inner'>
    <div class='inner-top'>
    日々コツコツと自分を成長させよう
    </div>
    <div class='inner-center'>
    成長を可視化することにより、自分がどれだけ成長しているのか
    </div>
    <div class='inner-bbottom'>
    実感してください
    </div>
  </div>

  <%# 達成項目の例%>
  <div class='achievement'>
    <div class='left-achi'>
      <div class='left-con'>
        <p>ex) 身につけたいスキル</p>
        <p>プログラミング能力</p>
        <p>コミュニケーション力</p>
        <p>英語力</p>
        <p>ビジネス知識</p>
        <p>雑学力</p>
      </div>
    </div>

    <div class='right-achi'>
    <p>能力値</p>
    <p>0</p>
    <p>0</p>
    <p>0</p>
    <p>0</p>
    <p>0</p>
    </div>

    <div class='add-value'>
    <p>+1</p>
    <p>+1</p>
    <p>+1</p>
    <p>+1</p>
    <p>+1</p>
    </div>

    <div class='right-content'>
    <p>
    これから身につけていく、スキルを1〜5個考えてみましょう
    </p>
    <p>
    ※左記は一例です
    </p>
    <p>
    チェックボックスにチェックを入れると、項目を達成したことになります
    </p>
    <p>
    項目を達成するごとに、自身のレベルが上がっていきます
    </p>
    </div>
  </div>

  <%# チェックボックスの例 %>
  <div class='example'>
    <div class='ex-parent'>
      example
    </div>

    <div class='ex-child'>
      <p>ex) プログラミング能力</p>
      <p><input type='checkbox' value="check1">
        CSSでflexboxを学習した
      </p>

      <p><input type='checkbox' value="check2">
        Rubyでifを使い条件分岐させてみた
      </p>

      <p><input type='checkbox' value="check3">
        画像投稿機能を実装してみた
      </p>

      <p><input type='checkbox' value="check4">
        deviseを導入して、ユーザー管理機能を実装してみた
      </p>

      <p><input type='checkbox' value="check5">
        MVCの流れを学習した
      </p>
    </div>
  </div>

  <div class='begin'>
    <div class='let-start'>
    Let's start!
    </div>
    <div class='start'>
    それでは初めてみましょう！
    <%= link_to '新規登録', new_user_registration_path, class: "bottom-sign-up" %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plus1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class='footer'>
<p>Copyright(C) NaaaR RESERVED.</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='logo'>
    <%= link_to image_tag("Logo.plus1.jpg", class:"plus1-icon"), "/" %>
  </div>

  <div class='top'>
    <ul class='login-logout'>
      <% if user_signed_in? %>
         <li><%= link_to "#{current_user.name}","#", class: "user-name" %></li> 
         <li><%= link_to 'my page', targets_path, class: "my-page"%></li>
         <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/targets/index.html.erb
<%= render "shared/header" %>

<div class="targets-main">
  <div class="targets-sub">
    <div class="targets-box">
      <div class="target">
        目標を決めましょう
        <span class="indispensable">必須</span>
      </div>
      <%= text_area :target, class:"target-text", id:"target", placeholder:"目標の設定" %>

      <div class="achivement">
        達成項目を設定しましょう
        <span class="indispensable">必須</span>
      </div>
      <%= text_area :achivement, class:"achivement-text", id:"achivement", placeholder:"達成項目の設定" %>

      <div class="enthusiasm">
        意気込みor今の気持ちを書いてみましょう
        <span class="indispensable">必須</span>
      </div>
      <%= text_area :enthusiasm, class:"enthusiasm-text", id:"enthusiasm" %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", "#", class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class='box'>
</div>